### ISSUE TITLE
Error fetching OpenAI models: 404 page not found

### ISSUE THREAD

**Issue by Maekfei** [Ikaros-521/GraphRAG-Ollama-UI#18]
已经都填好api base了 但是不知道为什么还是一直报404  

evn:
LLM_API_BASE=http://127.0.0.1:11434/v1
LLM_API_KEY=ollama
LLM_MODEL=qwen2:7b
EMBEDDINGS_API_BASE=http://127.0.0.1:11434/api
EMBEDDINGS_API_KEY=ollama
EMBEDDINGS_MODEL=nomic-embed-text:latest
CONTEXT_WINDOW=4096
SYSTEM_MESSAGE=You are a helpful AI assistant.
TEMPERATURE=0.5
MAX_TOKENS=1024
LLM_SERVICE_TYPE=openai_chat
EMBEDDINGS_SERVICE_TYPE=openai_embedding

settings

async_mode: threaded
cache:
  base_dir: cache
  type: file
chunks:
  group_by_columns:
  - id
  overlap: 64
  size: 512
claim_extraction:
  enabled: true
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 0
  prompt: prompts/claim_extraction.txt
cluster_graph:
  max_cluster_size: 10
community_report:
  max_input_length: 8000
  max_length: 2000
  prompt: prompts/community_report.txt
embed_graph:
  enabled: false
embeddings:
  async_mode: threaded
  llm:
    api_base: http://127.0.0.1:11434/api
    api_key: ollama
    concurrent_requests: 25
    model: nomic-embed-text:latest
    model_supports_json: true
    provider: openai_embedding
    type: openai_embedding
encoding_model: cl100k_base
entity_extraction:
  entity_types:
  - organization
  - person
  - geo
  - event
  max_gleanings: 0
  prompt: prompts/entity_extraction.txt
global_search:
  concurrency: 32
input:
  base_dir: input
  file_encoding: utf-8
  file_pattern: .*\.txt$
  file_type: text
  type: file
llm:
  api_base: http://127.0.0.1:11434/v1
  api_key: ollama
  concurrent_requests: 25
  max_tokens: 1024
  model: qwen2:7b
  model_supports_json: true
  provider: openai_chat
  temperature: 0.5
  type: openai
local_search: null
parallelization:
  num_threads: 50
  stagger: 0.3
reporting:
  base_dir: output/${timestamp}/reports
  type: file
skip_workflows: []
snapshots:
  graphml: true
  raw_entities: true
  top_level_nodes: true
storage:
  base_dir: output/${timestamp}/artifacts
  type: file
summarize_descriptions:
  max_length: 500
  prompt: prompts/summarize_descriptions.txt
umap:
  enabled: false

**Comment by Maekfei** [comment]
上个问题解决了 我也不确定中间问题出在哪 感觉是app.py那块 我换了别人写好的文件
qwen运行是没有问题的 但是换成别的垂直领域模型就报错create_base_entity_graph: Columns must be same length as key 请教各位大佬如何解决

**Comment by Ikaros-521** [comment]
模型很不稳定的，配合ollama来跑这套其实纯玄学

**Comment by Ikaros-521** [comment]
还是得换模型 继续试试

**Comment by Whis4ky** [comment]
> 上个问题解决了 我也不确定中间问题出在哪 感觉是app.py那块 我换了别人写好的文件 qwen运行是没有问题的 但是换成别的垂直领域模型就报错create_base_entity_graph: Columns must be same length as key 请教各位大佬如何解决

你好请问一下 我碰到了15:11:38,319 root ERROR Error getting OpenAI compatible embedding: 404 page not found 这个问题 是怎么回事

**Comment by Ikaros-521** [comment]
> > 上个问题解决了 我也不确定中间问题出在哪 感觉是app.py那块 我换了别人写好的文件 qwen运行是没有问题的 但是换成别的垂直领域模型就报错create_base_entity_graph: Columns must be same length as key 请教各位大佬如何解决
> 
> 你好请问一下 我碰到了15:11:38,319 root ERROR Error getting OpenAI compatible embedding: 404 page not found 这个问题 是怎么回事

接口地址应该不对。不过之后国庆看有没有空，准备同步下官方新版了，应该改了不少

**Comment by Whis4ky** [comment]
> > > 上个问题解决了 我也不确定中间问题出在哪 感觉是app.py那块 我换了别人写好的文件 qwen运行是没有问题的 但是换成别的垂直领域模型就报错create_base_entity_graph: Columns must be same length as key 请教各位大佬如何解决
> > 
> > 
> > 你好请问一下 我碰到了15:11:38,319 root ERROR Error getting OpenAI compatible embedding: 404 page not found 这个问题 是怎么回事
> 
> 接口地址应该不对。不过之后国庆看有没有空，准备同步下官方新版了，应该改了不少
我这边测试的时候用curl -X POST http://localhost:11434/api/embeddings -d '{"model":"snowflake-arctic-embed","prompt":"hi"}'
有回复 你方便看一下我的这个setting吗
async_mode: threaded
cache:
  base_dir: cache
  type: file
chunks:
  group_by_columns:
  - id
  overlap: 64
  size: 512
claim_extraction:
  enabled: true
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 0
  prompt: prompts/claim_extraction.txt
cluster_graph:
  max_cluster_size: 10
community_report:
  max_input_length: 8000
  max_length: 2000
  prompt: prompts/community_report.txt
embed_graph:
  enabled: false
embeddings:
  async_mode: threaded
  llm:
    api_base: http://127.0.0.1:11434/api/embeddings
    api_key: ollama
    concurrent_requests: 25
    model: snowflake-arctic-embed
    model_supports_json: true
    provider: openai_embedding
    type: openai_embedding
encoding_model: cl100k_base
entity_extraction:
  entity_types:
  - organization
  - person
  - geo
  - event
  max_gleanings: 0
  prompt: prompts/entity_extraction.txt
global_search:
  concurrency: 32
input:
  base_dir: input
  file_encoding: utf-8
  file_pattern: .*\.txt$
  file_type: text
  type: file
llm:
  api_base: http://localhost:11434/v1
  api_key: ${GRAPHRAG_API_KEY}
  concurrent_requests: 25
  max_tokens: 1024
  model: qwen2:latest
  model_supports_json: true
  provider: openai_chat
  temperature: 0.5
  type: openai
local_search: null
parallelization:
  num_threads: 50
  stagger: 0.3
reporting:
  base_dir: output/${timestamp}/reports
  type: file
skip_workflows: []
snapshots:
  graphml: true
  raw_entities: true
  top_level_nodes: true
storage:
  base_dir: output/${timestamp}/artifacts
  type: file
summarize_descriptions:
  max_length: 500
  prompt: prompts/summarize_descriptions.txt
umap:
  enabled: false

**Comment by Ikaros-521** [comment]
> > > > 上个问题解决了 我也不确定中间问题出在哪 感觉是app.py那块 我换了别人写好的文件 qwen运行是没有问题的 但是换成别的垂直领域模型就报错create_base_entity_graph: Columns must be same length as key 请教各位大佬如何解决
> > > 
> > > 
> > > 你好请问一下 我碰到了15:11:38,319 root ERROR Error getting OpenAI compatible embedding: 404 page not found 这个问题 是怎么回事
> > 
> > 
> > 接口地址应该不对。不过之后国庆看有没有空，准备同步下官方新版了，应该改了不少
> > 我这边测试的时候用curl -X POST http://localhost:11434/api/embeddings -d '{"model":"snowflake-arctic-embed","prompt":"hi"}'
> > 有回复 你方便看一下我的这个setting吗
> > async_mode: threaded
> > cache:
> > base_dir: cache
> > type: file
> > chunks:
> > group_by_columns:
> 
> * id
>   overlap: 64
>   size: 512
>   claim_extraction:
>   enabled: true
>   description: Any claims or facts that could be relevant to information discovery.
>   max_gleanings: 0
>   prompt: prompts/claim_extraction.txt
>   cluster_graph:
>   max_cluster_size: 10
>   community_report:
>   max_input_length: 8000
>   max_length: 2000
>   prompt: prompts/community_report.txt
>   embed_graph:
>   enabled: false
>   embeddings:
>   async_mode: threaded
>   llm:
>   api_base: http://127.0.0.1:11434/api/embeddings
>   api_key: ollama
>   concurrent_requests: 25
>   model: snowflake-arctic-embed
>   model_supports_json: true
>   provider: openai_embedding
>   type: openai_embedding
>   encoding_model: cl100k_base
>   entity_extraction:
>   entity_types:
> * organization
> * person
> * geo
> * event
>   max_gleanings: 0
>   prompt: prompts/entity_extraction.txt
>   global_search:
>   concurrency: 32
>   input:
>   base_dir: input
>   file_encoding: utf-8
>   file_pattern: .*.txt$
>   file_type: text
>   type: file
>   llm:
>   api_base: http://localhost:11434/v1
>   api_key: ${GRAPHRAG_API_KEY}
>   concurrent_requests: 25
>   max_tokens: 1024
>   model: qwen2:latest
>   model_supports_json: true
>   provider: openai_chat
>   temperature: 0.5
>   type: openai
>   local_search: null
>   parallelization:
>   num_threads: 50
>   stagger: 0.3
>   reporting:
>   base_dir: output/${timestamp}/reports
>   type: file
>   skip_workflows: []
>   snapshots:
>   graphml: true
>   raw_entities: true
>   top_level_nodes: true
>   storage:
>   base_dir: output/${timestamp}/artifacts
>   type: file
>   summarize_descriptions:
>   max_length: 500
>   prompt: prompts/summarize_descriptions.txt
>   umap:
>   enabled: false

仅供参考，不过这个接口调用会和url本身以及type有关
```
async_mode: threaded
cache:
  base_dir: cache
  type: file
chunks:
  group_by_columns:
  - id
  overlap: 64
  size: 512
claim_extraction:
  enabled: true
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 0
  prompt: prompts/claim_extraction.txt
cluster_graph:
  max_cluster_size: 10
community_report:
  max_input_length: 8000
  max_length: 2000
  prompt: prompts/community_report.txt
embed_graph:
  enabled: false
embeddings:
  async_mode: threaded
  llm:
    api_base: http://127.0.0.1:11434/api
    api_key: ${GRAPHRAG_API_KEY}
    concurrent_requests: 25
    model: nomic-embed-text:latest
    model_supports_json: true
    provider: openai_embedding
    type: openai_embedding
encoding_model: cl100k_base
entity_extraction:
  entity_types:
  - organization
  - person
  - geo
  - event
  max_gleanings: 0
  prompt: prompts/entity_extraction.txt
global_search:
  concurrency: 32
input:
  base_dir: input
  file_encoding: utf-8
  file_pattern: .*\.txt$
  file_type: text
  type: file
llm:
  api_base: http://127.0.0.1:11434/v1
  api_key: ${GRAPHRAG_API_KEY}
  concurrent_requests: 25
  max_tokens: 1024
  model: qwen2:latest
  model_supports_json: true
  provider: openai_chat
  temperature: 0.5
  type: openai
local_search: null
parallelization:
  num_threads: 50
  stagger: 0.3
reporting:
  base_dir: output/${timestamp}/reports
  type: file
skip_workflows: []
snapshots:
  graphml: true
  raw_entities: true
  top_level_nodes: true
storage:
  base_dir: output/${timestamp}/artifacts
  type: file
summarize_descriptions:
  max_length: 500
  prompt: prompts/summarize_descriptions.txt
umap:
  enabled: false

```
