### ISSUE TITLE
"Error executing verb "text_embed" in create_final_entities: list index out of range"这是什么错误

### ISSUE THREAD

**Issue by francis123455** [Ikaros-521/GraphRAG-Ollama-UI#23]
请问logs.json记录的报错如下是什么问题：
{"type": "error", "data": "Error executing verb "text_embed" in create_final_entities: list index out of range", "stack": "Traceback (most recent call last):\n File "/home/ubuntu/anaconda3/envs/chatchat/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 415, in _execute_verb\n result = await result\n File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/text_embed.py", line 105, in text_embed\n return await _text_embed_in_memory(\n File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/text_embed.py", line 130, in _text_embed_in_memory\n result = await strategy_exec(texts, callbacks, cache, strategy_args)\n File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/strategies/openai.py", line 62, in run\n embeddings = _reconstitute_embeddings(embeddings, input_sizes)\n File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/strategies/openai.py", line 171, in _reconstitute_embeddings\n embedding = raw_embeddings[cursor]\nIndexError: list index out of range\n", "source": "list index out of range", "details": null}
{"type": "error", "data": "Error running pipeline!", "stack": "Traceback (most recent call last):\n File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/run.py", line 320, in run_pipeline\n await inject_workflow_data_dependencies(workflow)\n File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/run.py", line 256, in inject_workflow_data_dependencies\n table = await load_table_from_storage(f"{id}.parquet")\n File "/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/run.py", line 242, in load_table_from_storage\n raise ValueError(msg)\nValueError: Could not find create_final_entities.parquet in storage!\n", "source": "Could not find create_final_entities.parquet in storage!", "details": null}
用的mistral和nomic-embed-text,之前使用利用graphrag包和ragtest目录在终端命令启动python -m graphrag.index --root ./ragtest是没问题的

**Comment by Ikaros-521** [comment]
Could not find create_final_entities.parquet 
有个需要使能
```
claim_extraction:
  enabled: true
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 0
  prompt: prompts/claim_extraction.txt
cluster_graph:
  max_cluster_size: 10
community_report:
  max_input_length: 8000
  max_length: 2000
  prompt: prompts/community_report.txt
```
